AWSTemplateFormatVersion: 2010-09-09
Description: Cloudformation template for deploying the mlb report generator lambda and s3 bucket


Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'scorecards.jjhsk.com'
      WebsiteConfiguration:
        ErrorDocument: '404.html'
        IndexDocument: 'index.html'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: False
        BlockPublicPolicy: False
        IgnorePublicAcls: False
        RestrictPublicBuckets: False

  SiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref SiteBucket
                - /*
            Principal: '*'
